### ISSUE TITLE
Support for more highlight groups

### ISSUE THREAD

**Issue by jacobrreed** [eldritch-theme/eldritch.nvim#2]
Brought up by @akthe-at  in a pull request they made. I have reworked the repo based on Folke's tokyonight

@akthe-at  if you want to give me a second pair of eyes on it, ive opened a branch `tokyo-rework`, if you change in your lua config for Eldritch:
```
{
  "eldritch-theme/eldritch-nvim",
  branch="rework-off-tokyo",
  lazy = false,
  priority = 1000,
  opts = { },
  config = function(_, opts)
    require("eldritch").setup(opts)
    vim.cmd([[colorscheme eldritch]])
  end,
}

```

**Comment by akthe-at** [comment]
Loading it up right now but I think your branch is `rework-off-tokyo`

**Comment by akthe-at** [comment]
Sorry didnt see the edit!

**Comment by jacobrreed** [comment]
> Sorry didnt see the edit!

no worries lol, just let me know, ill probably need to tweak colors here and there, i essentially copied tokyo night with some tweaks and deleted the alternate styles

**Comment by akthe-at** [comment]
Do you want me to use my previous screenshots as a reference for what colors you want associated with various highlights? This looks nice right now but is definitely a different look/feel at the moment compared with the other branch.

**Comment by jacobrreed** [comment]
what do you think personally, i tried to align it more with tokyo nights patterns

**Comment by jacobrreed** [comment]
this entire theme is very early in its life right now and I am totally open to a little collaboration and feedback, especially from its first users

**Comment by akthe-at** [comment]
There is something amiss with differentiating highlights. Here is tokyonight-night on a scratch/test python script:
![image](https://github.com/eldritch-theme/eldritch-nvim/assets/105152139/5f905ed2-36b5-40fe-9314-3fede021cdb0)

Now for the the dev branch of eldritch for me is below this, notice the repeated cyan in a lot of places.
![image](https://github.com/eldritch-theme/eldritch-nvim/assets/105152139/78269d7d-0178-412b-b281-237b06541f15)

**Comment by jacobrreed** [comment]
ok i will work on that

**Comment by jacobrreed** [comment]
also ive changed the repo from `eldritch-nvim` to `eldritch.nvim` to match other nvim plugins

**Comment by jacobrreed** [comment]
@akthe-at Ive pushed some updates, let me kow what you think, got rid of repetitive colors, added some darkening, I think will align more with the themes color patterns better. I still need to go through and change the highlight group for a bunch of plugins like Telescope and stuff but I think the LSP/Treesitter stufff should be good now, might need to test on a few more languages to be sure it flows well

**Comment by akthe-at** [comment]
I think things are moving along nicely! There is something still amiss when it comes to classes and their methods. I haven't had a chance to dig too deep and won't until tonight but here is what a quick glance shows:

![image](https://github.com/eldritch-theme/eldritch.nvim/assets/105152139/7bea91f4-7975-4a65-acbf-20677946e02d)

There is a slight difference between class and method highlights before the lsp (basedpyright) kicks in and starts giving semantic tokens.

**Comment by jacobrreed** [comment]
Are you referring to the blue and darker blue?

**Comment by akthe-at** [comment]
datetime.now().strftime(), the later two should match each other but not datetime in color

**Comment by jacobrreed** [comment]
Ok will look into it

**Comment by jacobrreed** [comment]
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/f23e717f-cc41-43fe-8bdd-112297dba207)
@akthe-at  To me im seeing datetime the "dark_cyan" color which is a more dark blue, and the now and strftime are cyan

**Comment by akthe-at** [comment]
> ![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/f23e717f-cc41-43fe-8bdd-112297dba207)
> @akthe-at  To me im seeing datetime the "dark_cyan" color which is a more dark blue, and the now and strftime are cyan

Super interesting, are you using pyright or basedpyright as an LSP in this photo? Or maybe another lsp all together?

**Comment by jacobrreed** [comment]
Using basedpyright to test against what you said
Just pushed again, give that a try and tell me if you still see that

**Comment by jacobrreed** [comment]
do you think its too conflicting of a color? I could change the dark cyan to something else maybe

**Comment by akthe-at** [comment]
> Using basedpyright to test against what you said
> Just pushed again, give that a try and tell me if you still see that

If it's still weird when I get home and check I will try to delete all my shada files, temp files, etc and double check and make sure I'm up to date on the lsp, etc. Your photo looks good and correct.

**Comment by akthe-at** [comment]
I do think that they are probably a little too close, here is gruvbox, rose pine and Tokyonight for comparison

![Screenshot_20240331-190417.png](https://github.com/eldritch-theme/eldritch.nvim/assets/105152139/21b1a128-fdb5-4962-b4e5-e7c214c94278)

![Screenshot_20240331-190506.png](https://github.com/eldritch-theme/eldritch.nvim/assets/105152139/b8ffeb1a-15aa-48c7-8c7f-a6244d88718f)

![Screenshot_20240331-190245.png](https://github.com/eldritch-theme/eldritch.nvim/assets/105152139/047ac221-8224-4826-bc3a-8e41cc56e00c)

**Comment by akthe-at** [comment]
Perhaps that pink or green from the palette? I think what draws me to this palette is that it feels like a mixture of dracula and Tokyonight

**Comment by jacobrreed** [comment]
ya let me play around and see what looks good

**Comment by jacobrreed** [comment]
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/9030655d-48ca-4345-a56d-cf1ead2cfef0)

**Comment by akthe-at** [comment]
I thought of it originally the other way around but I might like this more because the action is the bright part. I think that's fitting

**Comment by akthe-at** [comment]
OK so i got the latest commits on the development branch, all the highlights are working correctly and match yours as well. I think stuff is looking good in SQL, R, python, and htmldjango...I am not saying there isn't room to change anything but it looks a lot better than 24 hours ago...How are you feeling about it?

**Comment by akthe-at** [comment]
Couple of quick thoughts
string.documentation vs string vs string.html are all the same at the moment, not sure yet how I feel about that, I feel like I need a day of staring at the vibrant yellow text on an html page for a day of work to judge this. 

Could use some color for the Icons for Dashboard.nvim (  DashboardIcon = { fg = <something, currently cyan like the words next to it>}  )

**Comment by jacobrreed** [comment]
> Couple of quick thoughts string.documentation vs string vs string.html are all the same at the moment, not sure yet how I feel about that, I feel like I need a day of staring at the vibrant yellow text on an html page for a day of work to judge this.
> 
> Could use some color for the Icons for Dashboard.nvim ( DashboardIcon = { fg = <something, currently cyan like the words next to it>} )

will work on this

**Comment by jacobrreed** [comment]
> .documentation vs string vs string.html are all the same at the moment, not sure yet how I feel about that, I feel like I need

Can you give me an example of the html with text you speak of, also dashboard icon is already set you should see it as cyan

**Comment by akthe-at** [comment]
@jacobrreed I think the dark yellow for the string.html is perfect. regular strings passed into functions as arguments and documentation strings are the same elsewhere and I think that is normal/fine. I was just thrown off when all three were the same in all spots, especially with how vibrant that was on an html page with a ton of tailwindcss inline. However, your change looks great.

Regarding the Dashboard Icons I was just seeing if you wanted the text and Icon to match, it makes sense to keep it the same as the text that accompanies it but I could also see having the icons as one of the other main core eldritch palette colors 
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/105152139/123d6a9c-9132-4f66-8e13-dd52286c106e)

**Comment by jacobrreed** [comment]
ya let me change the dashboard icon to be the green
i think that fits bett

**Comment by akthe-at** [comment]
🔥

**Comment by jacobrreed** [comment]
merged to master, thanks for the help if you find anything else let me know

**Comment by akthe-at** [comment]
Looks great! I noticed that the folke theme options like dim_inactive don't seem to actually work even though the code looks the same as tokyonight? Does it dim an inactive background for you? Do you want me to open a new issue for this?

**Comment by jacobrreed** [comment]
ya cut another issue and ill look into it

**Comment by jacobrreed** [comment]
@akthe-at Does it work for you with tokyo night? I personally use tint.nvim so I dont think I could tell the difference, i turned tint off and I dont see it working either. Tested with tokyonight as well

**Comment by jacobrreed** [comment]
```
 NormalNC = { fg = c.fg, bg = options.transparent and c.none or options.dim_inactive and c.bg_dark or c.bg }, -- normal text in non-current windows
 ```

so if transparent is set it definitely wont work, but even if it is doesn't seem to make a difference

**Comment by akthe-at** [comment]
interesting...its not actually working right now on Tokyonight but definitely has in the past! This must be an upstream bug, I will file an issue there.

**Comment by jacobrreed** [comment]
> interesting...its not actually working right now on Tokyonight but definitely has in the past! This must be an upstream bug, I will file an issue there.

https://github.com/folke/tokyonight.nvim/issues/211

**Comment by akthe-at** [comment]
Nice find, that fix worked for me

**Comment by akthe-at** [comment]
Actually, I didn't even need to pass the background colors, just using this as my config fixed this issue.

```
  {
    "eldritch-theme/eldritch.nvim",
    priority = 1000,
    opts = {},
    config = function()
      require("eldritch").setup({
        dim_inactive = true,
        transparent = false,
        hide_inactive_statusline = true,
        lualine_bold = true,
      })
      vim.o.termguicolors = true
    end,
  },
```

**Comment by jacobrreed** [comment]
Ok ya, so transparent has to be false for it to work, ill make a note of it in the docs
