### ISSUE TITLE
Issue with color in rename mode

### ISSUE THREAD

**Issue by whitewolf185** [eldritch-theme/eldritch.nvim#6]
Hi! 
Could you please fix colors in rename mode?

In picture below, i was pressed rename function name and cannot see what text is selected or not.
(spoiler: it is selected)
![image](https://github.com/eldritch-theme/eldritch/assets/26437639/9e7271f3-20f4-4b35-96b8-9ad575397b93)

**Comment by whitewolf185** [comment]
Hi!
Here I cannot see what I've just choose

![image](https://github.com/eldritch-theme/eldritch.nvim/assets/26437639/575d8401-8700-4107-bbfb-e03f71f62095)

**Comment by jacobrreed** [comment]
> Hi! Here I cannot see what I've just choose
> 
> ![image](https://private-user-images.githubusercontent.com/26437639/324268480-575d8401-8700-4107-bbfb-e03f71f62095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzE3NTMsIm5iZiI6MTcxMzczMTQ1MywicGF0aCI6Ii8yNjQzNzYzOS8zMjQyNjg0ODAtNTc1ZDg0MDEtODcwMC00MTA3LWJiZmItZTAzZjcxZjYyMDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIwMzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNmZkNzdjNmYxNWY5MDJkZDFjNzcyOTgzODE5YmE5MDM5MTkzY2ViNmRmNTdkNzM0Yzg4OWY1NzMzZmYwYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3JttkgZoL0jJCAVFw8JLr5IxQjxHhq6KgDVm-WY4hg0)

Are you referring to the backdrop of the rename window? The functionality of where that window displays has nothing to do with the theme

**Comment by whitewolf185** [comment]
I thought maybe the whole background could be more lighter, like #4A4D6A 

It would be like this
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/26437639/774a6a61-067b-45de-9eb0-e2788d00d97f)

Also, I see this problem with files which were influenced by gitignore

**Comment by jacobrreed** [comment]
You can override any highlights or colors you want with on_colors or on_highlights functions in the confg for theme. I do agree that specific instance does look better you can open a PR and I can check it out

**Comment by whitewolf185** [comment]
Could you give me, please, a hint where those settings is?

I never changed themes before

**Comment by jacobrreed** [comment]
You'd have to check what highlight group that code rename action window iis in nvim, then you can find it in
https://github.com/eldritch-theme/eldritch.nvim/blob/master/lua/eldritch/groups   if it exists , if not you'll have to add an override line there for the highlight group name

**Comment by whitewolf185** [comment]
Thanks a lot!

I will try to figure it out and I'll try to make a PR when I get some free time

**Comment by jacobrreed** [comment]
@whitewolf185 
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/65251e2e-12b7-4dd7-bd9c-28a1b686c952)

This is what I see btw
