### ISSUE TITLE
NotifyBackground color is not set with transparency = false

### ISSUE THREAD

**Issue by sbmueller** [eldritch-theme/eldritch.nvim#9]
Hi, following up to #8 , the issue has been re-introduced by reverting the PR commit.
Debugging so far showed that when `transparency = false`, `transparent_bg_float` will be evaluated to `nil` as it is set to `colors.bg_float`, which is dynamically evaluated only after calling the `setup()` function:
https://github.com/eldritch-theme/eldritch.nvim/blob/588f39608b092d2092118ae81c1b1945ea532665/lua/eldritch/theme.lua#L26
https://github.com/eldritch-theme/eldritch.nvim/blob/588f39608b092d2092118ae81c1b1945ea532665/lua/eldritch/theme.lua#L727
https://github.com/eldritch-theme/eldritch.nvim/blob/588f39608b092d2092118ae81c1b1945ea532665/lua/eldritch/colors.lua#L76-L78

Screenshot from current master using default configuration:

![image](https://github.com/eldritch-theme/eldritch.nvim/assets/7465688/d8d815bc-6e96-415b-937f-082e02a3958c)

**Comment by jacobrreed** [comment]
Ya now make the other change, and then open something like Lazy and the background will be black instead of transparent

**Comment by jacobrreed** [comment]
Hmm, ya I'll take a look again today very odd

**Comment by jacobrreed** [comment]
> I really can't reproduce your issue @jacobrreed . With the commit from #8 , Lazy looks like this for me, there is no 100% black background at all: ![image](https://private-user-images.githubusercontent.com/7465688/338569851-14e3d132-49e5-4ecc-93e0-21a90846dbd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTY5ODEsIm5iZiI6MTcxODExNjY4MSwicGF0aCI6Ii83NDY1Njg4LzMzODU2OTg1MS0xNGUzZDEzMi00OWU1LTRlY2MtOTNlMC0yMWE5MDg0NmRiZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTQzODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmYwNzlmNmM3NWZlZWU5YmMwNjA4MTA3OWQyYmQ5NTRlNTkxZmExN2FhNzFmMzBhMTBjNWUxZjlmYmZmZDJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f82hM1aB2fdkW-DZMMpotqtQJ9udof2DPJq4gpRy-kg)
> 
> For me, this looks correct. I would really appreciate it if you could debug this on your end as I'm not sure what behavior you're observing and expecting.

Here is what i'm seeing with your change
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/64d2044b-3794-43c1-aa7a-98a4faa936ce)


Without your change:
![image](https://github.com/eldritch-theme/eldritch.nvim/assets/25580051/28c38ba4-f78a-4ac8-9795-9b4cab5d6da7)


My eldritch.nvim config:
```
return {
  dir = "~/dev/eldritch-workspace/eldritch.nvim", -- ignore this, it's just me testing locally
  -- "eldritch-theme/eldritch.nvim",
  priority = 1000,
  opts = {
    transparent = true,
  },
  config = function(_, opts)
    local eldritch = require("eldritch")
    eldritch.setup(opts)
    vim.cmd([[colorscheme eldritch]])
  end,
}

```

**Comment by jacobrreed** [comment]
> Hi, following up to #8 , the issue has been re-introduced by reverting the PR commit. Debugging so far showed that when `transparency = false`, `transparent_bg_float` will be evaluated to `nil` as it is set to `colors.bg_float`, which is dynamically evaluated only after calling the `setup()` function:
> 
> https://github.com/eldritch-theme/eldritch.nvim/blob/588f39608b092d2092118ae81c1b1945ea532665/lua/eldritch/theme.lua#L26
> 
> 
> https://github.com/eldritch-theme/eldritch.nvim/blob/588f39608b092d2092118ae81c1b1945ea532665/lua/eldritch/theme.lua#L727
> 
> 
> https://github.com/eldritch-theme/eldritch.nvim/blob/588f39608b092d2092118ae81c1b1945ea532665/lua/eldritch/colors.lua#L76-L78
> 
> Screenshot from current master using default configuration:
> 
> ![image](https://private-user-images.githubusercontent.com/7465688/338454110-d8d815bc-6e96-415b-937f-082e02a3958c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTcwNDYsIm5iZiI6MTcxODExNjc0NiwicGF0aCI6Ii83NDY1Njg4LzMzODQ1NDExMC1kOGQ4MTViYy02ZTk2LTQxNWItOTM3Zi0wODJlMDJhMzk1OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTQzOTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDlhNTliODI0YmQ0YmRjNTRhNmNkMmU3YTkxMDJiYjQ2MDg0NDYzNTkyNTc4ODJlMDA0Njk4ZjJhMTNjMzU5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x8hJ-AOMkBq3R08kNITNOvPlOfEmrhaPrO5q37Ct7zM)

As for this, if you set 
```
    background_colour = "#FFFFFF",
```

in your notify opts that warning should never appear and itll still work as expected

**Comment by jacobrreed** [comment]
oh i didnt realize you were doing transparency false let me check that

**Comment by jacobrreed** [comment]
hmm, transparency set to false in opts doesnt seem to actually work..

**Comment by jacobrreed** [comment]
@sbmueller can you try now with this branch `bg_float-fix` just set in your config to point to that branch

**Comment by sbmueller** [comment]
@jacobrreed ah ok, so I understood from your [comment](https://github.com/eldritch-theme/eldritch.nvim/pull/8#issuecomment-2159009510), you were using default setup, e.g. `transparency = false`.
The branch LGTM!

**Comment by sbmueller** [comment]
For tranparency to work for me, I needed to disable winblend, see https://github.com/neovim/neovim/issues/18576

**Comment by sbmueller** [comment]
See #10
